- README.md
- src/recon_trace.erl
I found I need to do this today to capture some traces for a few hours to a file.  I'm not sure if there was another way to do this, but this works for me and may be useful for others.
> add trace to pid other than group_leader()

- src/recon_trace.erl
I was looking through the recon_trace code and found that what the tracer prints for heap size is in-accurate, and the value it uses as reclaimed is completely wrong. I couldn't find a way to use recon to enable gc tracing, but I did:
```erlang
1> recon_trace:calls({lists,any,2},10,[{pid,self()}]).
1
2> erlang:trace(self(), true, [{tracer, element(2,erlang:trace_info(self(),tracer))}, garbage_collection]).
1
3> erlang:trace_info(self(), flags).
{flags,[garbage_collection,call]}
16:34:43.081556 <0.34.0> gc beginning -- heap 3067 bytes
16:34:43.083763 <0.34.0> gc finished -- heap 539 bytes
```
and it seems to work.
> Fix gc_* trace message information

- src/recon_lib.erl
- test/recon_lib_SUITE.erl
Fix for #35 
Also added the dumbest possible test suite. I can remove this module if you'd prefer.
> Avoid divide by zero in scheduler_usage/1 on lightly loaded systems.

- src/recon_trace.erl
I find myself typing the following a lot:
```erlang
recon_trace:calls({mod, func, fun(_) -> return_trace() end}, 2).
```
So I added a helper in validation (the atom  `trace` in the place of the arg fun) that is replaced with the above function.  It may need a better name.
> add trace helper

- src/recon_alloc.erl
- test/recon_alloc_SUITE.erl
This function returns all allocator options and statistics aggregated for each type. I find that this is easier to work with than the complete dump when looking for patterns of what is going on in a system.
> Add recon_alloc:allocators(types) to view stats across types

- src/recon_lib.erl
- test/recon_lib_SUITE.erl
Thanks to recon I was able to track down my first memory leak in production so thanks for writing this library!
Now for some context: I'm running elixir in production and this was a tiny stumbling stone when figuring out how to specify a pid when using `recon_trace.calls/3`. In erlang you'd probably never represent a pid as a binary so while this change certainly isn't necessary, I think it also doesn't hurt. It could also save the next guy from getting a "no function clause matching" error when attempting to use recon from elixir:
```
iex(4)> :recon_trace.calls {:prim_inet, :send, fn _ -> :return_trace end}, 10, pid: "<0.2342.45>"
** (FunctionClauseError) no function clause matching in :recon_lib.term_to_pid/1
```
I added a few tests for `recon_lib:term_to_pid/1`. It's not typical for a …
> Add binary support to recon_lib:term_to_pid/1

- src/recon_alloc.erl
A small fix for this build error:
./src/recon_alloc.erl, function allocators/1: at line 383: `-quote ended unexpectedly at line 386
edoc: skipping source file './src/recon_alloc.erl': {'EXIT',error}.
edoc: error in doclet 'edoc_doclet': {'EXIT',error}.
ERROR: doc failed while processing /wrkdirs/usr/ports/devel/erlang-recon/work/recon-2.3.3: {'EXIT',error}
*** Error code 1
> Fix quoting in documentation string.

- doc/overview.edoc
- rebar.config
- src/recon_lib.erl
- src/recon_rec.erl
- src/recon_trace.erl
- test/recon_rec_SUITE.erl
- test/records1.erl
- test/records2.erl
You tell recon where your record definitions are, and then recon_trace prints our records in a readable way, with field names. If you have big records then it saves lots and lots of time and effort.
> Formatting records according to their definitions

- src/recon_rec.erl
This PR fixes a minor bug which squashed all record fields if limit was defined as a list
> fixed bug in filtering record fields for display

- mix.exs
- src/recon.app.src
The goal is to be able to use Recon is an Elixir/mix(1)-based project.
If the project can only be built with Rebar, mix(1) complains and asks if it can download `rebar3`. Not convenient in the middle of an unattended offline build.
> Add minimal mix.exs

- src/recon_trace.erl
Using the `message/1` action function in a match-spec sets an additional
message (aka the PAM result) appended to the trace message sent.
> Support extra message in traces

- src/recon_trace.erl
Here is example
```
%%      ``recon_trace:calls({Mod,Fun,[{'_', [], [{return_trace}]}]}, Max, Opts)'',
```
So the type matchspec need include '_'
I met dialyzer complain this
> Fix type matchspec

- src/recon_alloc.erl
This merges back the values reported to the old format, but keeps a
"raw" version of things for people wanting to read and build on the new
format as well.
CC @garazdawi if you can take a look and double-check that my edits make sense.
I'm not 100% familiar with the new format and can't really find docs, so I went from
context across versions to make sure it kind of makes sense.
Fixes https://github.com/ferd/recon/issues/77
> Format OTP-23 allocator data to match internals

- src/recon_trace.erl
(not for dialyzer but human consumption)
Very minor thing: it happened to me that when I quickly looked at the option section of the docs online (http://ferd.github.io/recon/recon_trace.html#type-options) I initially thought that `io_server` option must be a pid (maybe recon does something special with it). I only later saw that the textual docs clearly state that it also can be an atom and looking at the code also makes this obvious.
> option io_server can also be an atom()

- src/recon_alloc.erl
Unless I'm mistaken (dealing with carriers in Erlang is not that easy), in `recon_alloc`, the `format_blocks`' `Acc` should be used when computing the total size and block count for an allocator. Otherwise, you get things like
```
{mbcs,[{blocks,77,77,77},
{blocks_size,7584,7584,7584},
{foreign_blocks,[{ets_alloc,[{count,45,45,49},
{size,45056,45056,46080}]},
{eheap_alloc,[{count,4,5,71},{size,243464,246480,246480}]},
{std_alloc,[{count,77,77,77},{size,7584,7584,7584}]}]},
{raw_blocks,[{binary_alloc,[{count,1714,1715,1715},
{size,1804080,1882840,1882840}]},
{ets_alloc,[{count,45,45,49},{size,45056,45056,46080}]},
{eheap_alloc,[{count,4,5,71},{size,243464,246480,246480}]},
{std_alloc,[{count,77,77,77},{size,7584,7584,7584}]}]},
```
when calling `recon_alloc:allocators/0` (and …
> Accumulate all block entries in format_blocks

- .github/workflows/ci.yml
- src/recon.erl
While trying to check if we'd run into errors come OTP 24, I figured I could get rid of the last remaining `dialyzer`-issued warnings, which is why I included it in CI.
(we'd [discussed this issue, around 2 years ago](https://github.com/ferd/recon/issues/70), but at that time I didn't remember this solution)
> Increase strictness

- script/erl_crashdump_analyzer.sh
ran into errors when "binary" and "code" strings appeared before the expected count. resulting in an error when it tried to /(1024*1024), found that ensuring we use ^ to define start of word solved this. I updated all of the proposed strings to account for a chance that this occurs for others.
./erl_crashdump_analyzer.sh: line 27: let: m=0x00007f4da25e6358:SReturn addr 0xACE80DB8 (*redacted*_binary:to_utf8/1 + 128)/(1024*1024): syntax error in expression (error token is ":SReturn addr 0xACE80DB8 (*redacted*_binary:to_utf8/1 + 128)/(1024*1024)")
> Handle unexpected strings containing "binary"/"code" in crashdump analyzer

- .github/workflows/ci.yml
- src/recon.erl
- src/recon_alloc.erl
While investigating a virtual memory issue I found that none of the supercarrier statistics were included in the snapshot. This PR includes those.
> Include erts_mmap in snapshot to help debug VM issues

- src/recon_alloc.erl
In OTP-27, `+0.0` and `-0.0` will no longer be the exact number so they added a compilation warning in OTP-26.1 to warn when a float 0.0 is getting match without specifying the sign:
```
rebar3 compile                                                                                                                                                                               0s
===> Verifying dependencies...
===> Analyzing applications...
===> Compiling recon
src/recon_alloc.erl:706:7: Warning: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 instead.
src/recon_alloc.erl:706:11: Warning: matching on the float 0.0 will no longer also match -0.0 in OTP 27. If you specifically intend to match 0.0 alone, write +0.0 …
```
> remove compilation warning in OTP26.1

- .github/workflows/ci.yml
Some stuff is so old that containers no longer contain library versions required to run dependencies.
> Bump CI versions

- src/recon.app.src
The `recon:source/1` function calls `erl_prettypr` from `syntax_tools` application. This dependency was missing from the `.app` - this resulting in incomplete builds in some cases
> Add missing dependency on syntax_tools

- src/recon_trace.erl
Sometimes it is handy to implement some additional filtering in a custom formatter function. In this case the formatter can return the empty string if it wants to ignore a trace message. Optimize the formatting so in the empty string case it does not send an io request to the IO server. This saves some message passing and avoids a "flickering prompt" effect (when the empty string is printed) in case of 1000s of ignored trace messages per second.
Tested manually in `rebar3 shell` (before this patch prompt `4>` used to "flicker"):
```
1> F = fun F() -> lists:nth(2, [1,2,3]), timer:sleep(1), F() end.
#Fun<erl_eval.20.125776118>
2> spawn(fun() -> F() end).
<0.198.0>
3> recon_trace:calls({lists, nth, 2}, 1000, [{formatter, fun(_) -> "" end}]).
1
Recon tracer rate limit tripped.
4>
```
> Optimize (not) printing empty string from formatter

- src/recon.erl
- test/recon_SUITE.erl
Fixes https://github.com/ferd/recon/issues/95
> Prevent crash when calling binary_memory on a dead process
